config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "blogs#index"

  resources :blogs, except: [:destroy], param: :slug do
    resources :posts do
      resources :comments, module: 'posts', only: [:create]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
  has_many :posts

  validates :title, :slug, presence: true
  validates :slug, { uniqueness: { case_sensitive: false } }

  def to_param
    slug
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  after_create_commit { broadcast_append_to post.comments_channel }
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :blog

  has_many :comments

  validates :title, presence: true
  validates :body, length: { minimum: 20, maximum: 500 }

  def comments_channel
    "post_#{id}_comments"
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true

  has_one :blog
  has_many :posts
  has_many :comments

  def to_s
    name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

  def index
    @blogs = Blog.all.sample(5)
  end

  def show
    @blog = Blog.find_by!(slug: params[:slug])
  end

  def new
    @blog = current_user.build_blog
  end

  def create
    @blog = current_user.build_blog(blog_params)

    if @blog.save
      flash[:notice] = 'Blog succesfully created!'
      redirect_to blogs_path
    else
      render :new
    end
  end

  def edit
    @blog = current_user.blog
  end

  def update
    @blog = current_user.blog

    if @blog.update(blog_params)
      flash[:notice] = 'Blog succesfully updated!'
      redirect_to blogs_path
    else
      render :edit
    end
  end

  private

  def blog_params
    params.require(:blog).permit(:description, :slug)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = Comment.new(user_id: params[:user_id], post_id: params[:post_id], body: comment_params[:body])

    if @comment.save
    else
    end
  end

  def update
    @comment = Comment.find(params[:id])

    if @comment.update(comment_params)
    else
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/posts/comments_controller.rb
module Posts
  class CommentsController < ApplicationController

    def create
      @comment = post.comments.new(user: current_user, body: comment_params[:body])

      respond_to do |format|
        if @comment.save
          format.html { redirect_to [post.blog, post] }
        else
        end
      end
    end

    def update
      @comment = Comment.find(params[:id])

      if @comment.update(comment_params)
      else
      end
    end

    private

    def post
      Post.find(params[:post_id])
    end

    def comment_params
      params.require(:comment).permit(:body)
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: %i[edit update destroy show]

  def new
    @post = current_user.blog.posts.new
  end

  def show
    @comments = @post.comments
  end

  def create
    @post = current_user.blog.posts.new(post_params)
    @post.user = current_user

    if @post.save
      flash[:notice] = 'Post succesfully created!'
      redirect_to @post.blog
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      flash[:notice] = 'Post succesfully updated!'
      redirect_to @post.blog
    else
      render :edit
    end
  end

  def destroy
    @post.destroy

    flash[:notice] = 'Post deleted successfully!'
    redirect_to @post.blog
  end

  private

  def find_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def user_created_blog?
    current_user && current_user.blog && current_user.blog.persisted?
  end

  def datetime_signature_s(record)
    "Written by #{record.user} at #{l record.created_at, format: :short}"
  end

  def errors_for(object, options = {})
    if object && object.errors.any?
      content_tag(:div, class: 'card') do
        concat(content_tag(:div, class: 'card-header') do
          message_description = options[:message_title].present? ? options[:message_title] : ''
            "#{message_description} #{object.class.model_name.human.downcase}"
        end)
        concat(content_tag(:div, class: 'card-body') do
          concat(content_tag(:ul) do
            object.errors.full_messages.each do |msg|
              concat content_tag(:li, msg)
            end
          end)
        end)
      end
    end
  end
end

app/views/application/_navbar.html.erb
<nav class="navbar navbar-light bg-light navbar-expand mb-5 p-2">
  <%= link_to 'Mini Blog', root_path, class: 'navbar-brand mr-3' %>

  <% if user_signed_in? %>
    <% blog = current_user.blog %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <% if user_created_blog? %>
      <div class="collapse navbar-collapse">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <%= link_to 'New Post', [:new, blog, :post] %>
          </li>
          <li class="nav-item">
            <%= link_to 'Your Blog', blog %>
          </li>
        </ul>
      </div>
    <% end %>

    <div class="collapse navbar-collapse justify-content-end">
      <ul class="navbar-nav ml-auto">
        <% if user_created_blog? %>
          <li class="nav-item">
            <%= link_to 'Edit Blog', [:edit, blog] %>
          </li>
        <% end %>
        <li class="nav-item">
          <%= link_to 'Edit Profile', edit_user_registration_path(current_user) %>
        </li>
         <li class="nav-item">
          <%= link_to 'Log out', destroy_user_session_path, method: :delete %>
        </li>
      </ul>
    </div>
  <% else %>
    <div class="collapse navbar-collapse justify-content-end">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <%= link_to 'Sign in', new_user_session_path %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign up', new_user_registration_path %>
        </li>
      </ul>
    </div>
  <% end %>
</nav>

app/views/blogs/_form.html.erb
<div class='row'>
  <div class='border rounded p-5'>
    <%= form_for @blog do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :description %>
        <%= f.text_field :description, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :slug %>

        <div class="input-group">
          <span class="input-group-text"><%= blogs_url %>/</span>
          <%= f.text_field :slug, class: 'form-control' %>
        </div>
      </div>

      <div class="form-group">
        <%= f.submit class: 'btn btn-primary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/blogs/edit.html.erb
<h3>Edit your blog!</h3>

<%= render 'form' %>

app/views/blogs/index.html.erb
<% if user_signed_in? && !user_created_blog? %>
  <div class='text-center mb-5'>
    <%= link_to 'CREATE YOUR BLOG', new_blog_path, class: 'btn btn-success btn-lg' %>
  </div>
<% end %>

<div class='row'>
  <h3>Discover new blogs:</h3>

  <% @blogs.each do |blog| %>
    <div class='border rounded m-3 p-5'>
      <%= link_to blog.title, blog, class: "title-link" %></>
      <hr/>
      <p><%= blog.description %></p>
    </div>
  <% end %>
</div>

app/views/blogs/new.html.erb
<h3>Welcome to your new blog!</h3>

<%= render 'form' %>

app/views/blogs/show.html.erb
<div class='row'>
  <h3><%= @blog.title %></h3>
</div>

<div class='row'>
  <% @blog.posts.includes(:user).each do |post| %>
    <div class='border rounded m-3 p-5'>
      <%= link_to post.title, [@blog, post] %></>
      <p><%= datetime_signature_s(post)%></p>
      <p><%= simple_format post.body %></p>
    </div>
  <% end %>
</div>

app/views/comments/_comment.html.erb
<div class='row border rounded p-3'>
  <small><p><%= datetime_signature_s(comment)%> </p></small>
  <%= simple_format comment.body %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Desafio</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'navbar' %>

    <% if flash.any? %>
      <div class='row text-center m-2'>
        <p class="notice" style='color: green;'><%= notice %></p>
        <p class="alert" style='color: red;'><%= alert %></p>
      </div>
    <% end %>

    <div class='container'>
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<div class='row'>
  <div class='border rounded p-5'>
    <%= form_for [@post.blog, @post] do |f| %>
      <%= errors_for(@post, { message_title: 'Errors'}) %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.submit class: 'btn btn-primary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/edit.html.erb
<h3>Edit Post</h3>

<%= render 'form' %>

app/views/posts/new.html.erb
<h3>New Post</h3>

<%= render 'form' %>

app/views/posts/show.html.erb
<%= turbo_stream_from @post.comments_channel %>

<div class='row'>
  <h3><%= @post.title %></h3>
  <small><p><%= datetime_signature_s(@post)%> </p></small>
</div>

<div class='row border rounded p-5'>
  <%= simple_format @post.body %>

  <div class='mt-3 d-flex flex-row-reverse'>
    <%= link_to 'Edit', [:edit, @post.blog, @post], class: 'btn btn-primary' %>
    <%= link_to 'Delete', [@post.blog, @post], method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure?' } %>
  </div>
</div>


<div class='row'>
  <%= turbo_frame_tag :comments_form do %>
    <%= form_for [@post.blog, @post, Comment.new] do |f| %>
      <%= f.label :body %>
      <%= f.text_area :body %>

      <%= f.submit %>
    <% end %>
  <% end %>

  <%= turbo_frame_tag @post.comments_channel do %>
    <%= render @post.comments.order(:created_at) %>
  <% end %>
</div>